/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 glb/MonitorV3.glb -o src/models/Monitor.tsx 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Cube_1: THREE.Mesh
    Cube_2: THREE.Mesh
  }
  materials: {
    Monitor: THREE.MeshPhysicalMaterial
    Case: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/MonitorV3.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.907, 0]} scale={[1.337, 1, 1]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Monitor} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Case} />
      </group>
    </group>
  )
}

useGLTF.preload('/MonitorV3.glb')
